name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Test with Maven
        run: mvn test

      - name: Build Docker image
        run: docker build -t seu-usuario/seu-app:${{ github.sha }} .

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag seu-usuario/seu-app:${{ github.sha }} seu-usuario/seu-app:latest
          docker push seu-usuario/seu-app:latest

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Staging
        run: docker-compose -f docker-compose.yml up -d

  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Production
        run: docker-compose -f docker-compose.yml up -d
